name       : soundtouch
version    : 1.9.2
release    : 2
source     :
    - http://www.surina.net/soundtouch/soundtouch-1.9.2.tar.gz : caeb86511e81420eeb454cb5db53f56d96b8451d37d89af6e55b12eb4da1c513
license    : LGPL-2.1
summary    : Audio processing library.
component  : multimedia.library
emul32     : yes
description: |
    Open-source audio processing library that allows changing the sound tempo, pitch and playback rate parameters independently from each other.
setup      : |
    $workdir/bootstrap
    %configure
build      : |
    %make
install    : |
    %make_install
