name       : soundtouch
version    : 2.3.1
release    : 5
source     :
    - https://www.surina.net/soundtouch/soundtouch-2.3.1.tar.gz : 6900996607258496ce126924a19fe9d598af9d892cf3f33d1e4daaa9b42ae0b1
license    : LGPL-2.1-or-later
summary    : Audio processing library.
component  : multimedia.library
emul32     : yes
description: |
    Open-source audio processing library that allows changing the sound tempo, pitch and playback rate parameters independently from each other.
setup      : |
    $workdir/bootstrap
    %configure
build      : |
    %make -j
install    : |
    %make_install
