name       : soundtouch
version    : 2.1.0
release    : 4
source     :
    - https://gitlab.com/soundtouch/soundtouch/-/archive/2.1.0/soundtouch-2.1.0.tar.bz2 : 3fb740c7ac4b304342fbf11a91d14fa3e296269b9fec6266609c4620477d0ad6
license    : LGPL-2.1-or-later
summary    : Audio processing library.
component  : multimedia.library
emul32     : yes
description: |
    Open-source audio processing library that allows changing the sound tempo, pitch and playback rate parameters independently from each other.
setup      : |
    $workdir/bootstrap
    %configure
build      : |
    %make
install    : |
    %make_install
