name       : soundtouch
version    : 2.0.0
release    : 3
source     :
    - http://www.surina.net/soundtouch/soundtouch-2.0.0.tar.gz : d224f7d1421b5f8e74a74c85741345bd9802618a40ae30ce5b427a5705c89d25
license    : LGPL-2.1
summary    : Audio processing library.
component  : multimedia.library
emul32     : yes
description: |
    Open-source audio processing library that allows changing the sound tempo, pitch and playback rate parameters independently from each other.
setup      : |
    $workdir/bootstrap
    %configure
build      : |
    %make
install    : |
    %make_install
